### ISSUE TITLE
Cyrillic support in gcode file names.

### ISSUE THREAD

**Issue by V-N-U** [jadonmmiller/UltimateDuetMenuSystem#4]
Cyrillic (Russian) names are not displayed. Instead, empty characters.

**Comment by jadonmmiller** [comment]
Hmm... Thanks for your feedback, and that definitely should be fixed!

Unfortunately, that's an issue with the firmware that runs on the Duet control boards. I suggest you try posting on the [Duet forum](https://duet3d.com/forum) and hopefully they can help you.
