### ISSUE TITLE
 Possibility to set negative temperature from the main screen

### ISSUE THREAD

**Issue by V-N-U** [jadonmmiller/UltimateDuetMenuSystem#5]
When manually setting the temperature from the main screen, you can set the temperature with a "-"

**Comment by jadonmmiller** [comment]
Good morning, and thanks for your interest!

Unfortunately, I don't think there's a way of fixing that with the current firmware support. [Here's](https://duet3d.dozuki.com/Wiki/Duet_2_Maestro_12864_display_menu_system) the help page discussing Duet menu systems, and I suggest you submit your bug on the [forum](forum.duet3d.com).

The Duet menu infrastructure was promised a full revamp a few years ago, but it hasn't happened yet.
