### ISSUE TITLE
it is not possible to set the bed heating via the display menu

### ISSUE THREAD

**Issue by V-N-U** [jadonmmiller/UltimateDuetMenuSystem#6]
The main menu has manual settings for the temperature of the nozzle and bed. The nozzle temperature is set normally. The bed temperature is set but the heating is not activated. In the end, heating does not occur. If you activate the bed through DWC, then the bed starts.

![Снимок экрана 2021-12-09 011706](https://user-images.githubusercontent.com/91668195/145293373-db2fc1c4-4ca5-41d7-b436-d3c5b9250560.png)

![photo_2021-12-09_01-18-19](https://user-images.githubusercontent.com/91668195/145293549-10c230c9-e0be-45fb-a6ba-b1b1f14c02f2.jpg)

![Снимок экрана 2021-12-09 011912](https://user-images.githubusercontent.com/91668195/145293665-4418a055-0776-4c07-bc61-6f54a27389bf.png)

![Снимок экрана 2021-12-09 012036](https://user-images.githubusercontent.com/91668195/145293871-1692f047-f00b-4ee8-be37-5a3ae4be4d26.png)

**Comment by Moorviper** [comment]
Yes i can confirm at my printer i have the same issue.

**Comment by V-N-U** [comment]
> Да, я могу подтвердить на своем принтере, что у меня такая же проблема.

This problem will be solved in 3.4 rc. I raised the relevant topic on the forum. dc42 has already solved it.

**Comment by jadonmmiller** [comment]
@V-N-U Thanks a lot! I haven't had time to look into this lately.

Do you have a link to the forum post?

**Comment by V-N-U** [comment]
> @VNU Большое спасибо! У меня не было времени разбираться в этом в последнее время.
> 
> У вас есть ссылка на пост на форуме?
link to the topic: https://forum.duet3d.com/topic/26770/setting-the-temperature-using-12864-mini/26?_=1642254639190
