### ISSUE TITLE
a bit of a quality of life improvement

### ISSUE THREAD

**Issue by MrBlackmidi** [jadonmmiller/UltimateDuetMenuSystem#7]
is it possible for it to beep once the knob has been pressed? like the prusa mini beeps.

**Comment by jadonmmiller** [comment]
Hey, that's a great question!

Unfortunately, the Duet's 12864 display system is fairly closed from a user's viewpoint, and I don't think you can control hardware functions like that without modifying the firmware.

However, I would recommend that you ask about it on the Duet forums, linked below. They're a great community, and very knowledgeable!

https://forum.duet3d.com/
